### ISSUE TITLE
Clarification on OSSEC server and agent

### ISSUE THREAD

**Issue by yhuanghamu** [awslabs/hids-cloudwatchlogs-elasticsearch-template#2]
According to the documentation of OSSEC, An `OSSEC server` will monitor and analyse the log from `remote agents`. Although it is not clearly clarified in their documentation, a server should be able to monitor itself too.

If my understanding is correct, i don't see remote agents are installed. Instead, two OSSEC servers are installed and the alerts.json are piped to lambda function via cloudwatch log agents.

**Comment by cgulliver** [comment]
The agent is deployed in "local" install mode where the agent and monitoring components are deployed on each node so that it can run locally.
