### ISSUE TITLE
CloudFormation Error - The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions.

### ISSUE THREAD

**Issue by HGS-shoust01** [awslabs/hids-cloudwatchlogs-elasticsearch-template#3]
When creating with CloudFormation I get the following error:

The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException

![screenshot from 2019-02-27 12-07-20](https://user-images.githubusercontent.com/35959582/53489262-a766b480-3a88-11e9-8b97-4bc24f7c6953.png)

I will create a pull request that updates to nodejs8.10.

**Comment by cgulliver** [comment]
Merged
